This notebook is modified from Yuheng Wang's instruction

## **OpenAI Gym, PyBullet and PyBulletGym Installation**
[Click here to see Gym documentaion](https://gym.openai.com/docs/)

[Click here to see PyBullet documentaion](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA)

[Click here to see PyBulletGym page](https://github.com/benelot/pybullet-gym)

**Before we start, first update the apt-get tool in the given machine.**

In [1]:
!apt-get update


E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)


Most of the requirements of python packages are already fulfilled on Colab. To run Gym, you have to install prerequisites like xvbf,opengl & other python-dev packages using the following codes.

In [2]:
!pip install gym
!apt-get install python-opengl -y
!apt install xvfb -y

/bin/bash: pip: command not found
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?


In [ ]:
# For rendering environment, you can use pyvirtualdisplay. 
!pip install pyvirtualdisplay
!pip install piglet

In [ ]:
!pip install pybullet==2.5.9

In [ ]:
# Please use this version with several bugs fixed 
!git clone https://github.com/LostXine/pybullet-gym.git

In [ ]:
cd pybullet-gym/
!git checkout myfix

In [ ]:
!pip install -e .

** Now import everything and test them.**

In [1]:
import gym
from gym import logger as gymlogger
gymlogger.set_level(40) # error only
import pybulletgym  # register PyBullet enviroments with open ai gym

import numpy as np

# Colab comes with PyTorch
import torch
import torch.nn as nn
import torch.autograd as autograd

In [2]:
#define the simulated environment we are going to use
env = gym.make("InvertedPendulumMuJoCoEnv-v0")
#check out the pacman action space!
print(env.action_space)

# should return a state vector if everything worked (value doesn't matter)
env.reset()

Box(-1.0, 1.0, (1,), float32)


array([0.        , 0.09671903, 0.05298162, 0.99531174, 0.9985955 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ], dtype=float32)

In [3]:
env = gym.make("Walker2DMuJoCoEnv-v0")
print(env.action_space)

env.reset()

WalkerBase::__init__
Box(-1.0, 1.0, (6,), float32)


array([-0.0807218 ,  0.06507554,  0.03427074,  0.08719555, -0.01863771,
        0.09976987,  0.05415711, -0.04832714,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [4]:
env = gym.make("HalfCheetahMuJoCoEnv-v0")
print(env.action_space)

env.reset()

WalkerBase::__init__
Box(-1.0, 1.0, (6,), float32)


array([-0.06263518,  0.05273381, -0.09318163, -0.01394131, -0.08216418,
        0.03667672, -0.0572006 ,  0.02795838,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

** Congratulation! Now you can play with your RL agent! **