This notebook is modified from Yuheng Wang's instruction

## **OpenAI Gym, PyBullet and PyBulletGym Installation**
[Click here to see Gym documentaion](https://gym.openai.com/docs/)

[Click here to see PyBullet documentaion](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA)

[Click here to see PyBulletGym page](https://github.com/benelot/pybullet-gym)

**Before we start, first update the apt-get tool in the given machine.**

In [ ]:
!apt-get update

Most of the requirements of python packages are already fulfilled on Colab. To run Gym, you have to install prerequisites like xvbf,opengl & other python-dev packages using the following codes.

In [ ]:
!pip install gym
!apt-get install python-opengl -y
!apt install xvfb -y

In [ ]:
# For rendering environment, you can use pyvirtualdisplay. 
!pip install pyvirtualdisplay
!pip install piglet

In [ ]:
!pip install pybullet==2.5.9

In [ ]:
# Please use this version with several bugs fixed 
!git clone https://github.com/LostXine/pybullet-gym.git

In [ ]:
cd pybullet-gym/

In [ ]:
!pip install -e .

** Now import everything and test them.**

In [1]:
import gym
from gym import logger as gymlogger
gymlogger.set_level(40) # error only
import pybulletgym  # register PyBullet enviroments with open ai gym

import numpy as np

# Colab comes with PyTorch
import torch
import torch.nn as nn
import torch.autograd as autograd

In [2]:
#define the simulated environment we are going to use
env = gym.make("InvertedPendulumMuJoCoEnv-v0")
#check out the pacman action space!
print(env.action_space)

# should return a state vector if everything worked (value doesn't matter)
env.reset()

current_dir=/home/xine/.local/lib/python3.6/site-packages/pybullet_envs/bullet
options= 
Box(1,)
options= 


array([[0.        , 0.02202127],
       [0.        , 0.        ]])

In [3]:
env = gym.make("Walker2DMuJoCoEnv-v0")
print(env.action_space)

env.reset()

WalkerBase::__init__
options= 
Box(6,)
options= 


array([-0.061337  , -0.07952981, -0.03836122, -0.02394576, -0.06278449,
        0.03910355,  0.09659133, -0.03758235,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [4]:
env = gym.make("HalfCheetahMuJoCoEnv-v0")
print(env.action_space)

env.reset()

WalkerBase::__init__
options= 
Box(6,)
options= 


array([-0.06321356, -0.05333329,  0.06983914,  0.08414947, -0.00852981,
       -0.03788561, -0.05328716,  0.08772658,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

** Congratulation! Now you can play with your RL agent! **